### ISSUE TITLE
1. Review of Project description and documentation

### ISSUE THREAD

**Issue by nshirzad** [AxelAxhag/StonksSim#34]
Beskrivning och dokumentation av projektet är ganska tydligt skriven.
Det finns bra instruktioner om hur man ska köra programmet.
Det finns tydliga terminal-komando som hjälper till användaren med hur hen ska använda programmet.
Det kan vara bra dock om ni listar ut vilka stocks det går att köpa.
Tydliga kodkommentarer finns. 
Generellt ser projekt beskrivningen och dokumentationen bra ut.

**Comment by AxelAxhag** [comment]
Tack för feedbacken!
