### ISSUE TITLE
Use of Branching and Pull Requests

### ISSUE THREAD

**Issue by Infinity0303** [AxelAxhag/StonksSim#35]
Flera olika Branches används och Pull Requests har används för att mergea ihop de olika branches till main branchen. 
Oftast har samma person som har skapat pull requesten mergeat den. - Försök att låta någon annan i gruppen mergea den. 
Branches har tagits bort när det har används klart, vilket inte är något som vi har gjort, vi har låtit alla våra branches varit kvar.

**Comment by AxelAxhag** [comment]
Ja, vi tänkte att det inte spelade någon roll om man tog bort branches då det ändå finns sparade commit logs men det kanske är bäst att man behåller dem. Kan också hålla med att båda borde egentligen granska men det gjordes verbalt när det var en merge conflict
